apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: mydaemonset
  labels:
    app: myweb
    env: prod
spec:
  selector:
    matchLabels:
      app: myweb
      env: prod
  template:
    metadata:
      name: mydaemonsetpod
      labels:
        app: myweb
        env: prod
    spec:
      containers:
        - name: mydaemoncontainer
          image: nginx
          ports:
            - containerPort: 80
